# Generated by Django 4.0.3 on 2022-04-06 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('deptt', models.CharField(max_length=15)),
                ('address', models.TextField()),
            ],
        ),
    ]
